### ISSUE TITLE
词库来自？

### ISSUE THREAD

**Issue by Xuanwo** [wszgxa/tra#1]
可以帮助添加单词啊什么的么？

**Comment by Xuanwo** [comment]
我错了- -，百度翻译。。

**Comment by wszgxa** [comment]
=。=

**Comment by Xuanwo** [comment]
其实=  =，我是想能不能用本地的词库。
毕竟，我要是想用到这玩意儿肯定是网络状况不佳= =

**Comment by wszgxa** [comment]
其实逻辑很简单。如果有单词的数据库能搭建到本地就可以。但是没有现成的库。。。一个一个添加太麻烦了。

**Comment by Xuanwo** [comment]
唉= =，没关系，这个挺好的。实现我自己的需求看来得要自己造个轮子了。、。
